#spring.application.name=userservice
spring:
  application:
    name: USER-SERVICE
  profiles:
    active:
      - local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 9092